### ISSUE TITLE
Small typo carat vs. karat

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/mwnd-issues#14]
https://classroom.udacity.com/courses/ud899-gwg/lessons/42383e89-ac6a-491a-b7d0-198851287bbe/concepts/7c7be588-31e9-4c62-9dad-ecf23f943b19

I found just a minor typo in the Grow with Google Web Specialist Intermediate track. As someone with a passion for rocks and gemstones (I know probably lame) the lesson describes the weight of quartz in 'karat' and it should be 'carat'.

Karat describes the weight of gold. 
Carat is reserved for the weight of gemstones and diamonds.

'Destructuring values from an object 
const gemstone = { 
type: 'quartz', 
color: 'rose', 
karat: 21.29 
};

const {type, color, karat} = gemstone;

console.log(type, color, karat); 
Prints: quartz rose 21.29'

Ticket #716158

**Comment by forbiddenvoid** [comment]
Fixed
