### ISSUE TITLE
Lesson 1 Quiz 7 - quiz does not detect correct DPR

### ISSUE THREAD

**Issue by LordZnarf** [udacity/mwnd-issues#18]

**Comment by LordZnarf** [comment]
![quiz.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a857cd6146639001284da03/125516c66e82c728ace21e0d46f9819339c0cfeb9ffbb049a15ee4d67304722a2f53a17a20d1e179eb477e595f5f46f912515815adfe9b37b4f46d2ede0356b49b381d66cc2f10a5b2831abe09bc298c4681b3b98d4ad2a5.PNG)
The problem is, that chrome seems to have a precision issue. Checking the DPR via console logs:

`> window.devicePixelRatio`
`< 3.4999999403953552`

It's maybe related to Microsoft Windows scaling, but the quiz should complete.

As a student a workaround is to set the devicePixelRatio via developer console, as Chrome seems to accept that:
`window.devicePixelRatio = 3.5`
and the quiz completes

**Comment by forbiddenvoid** [comment]
Fixed. Floating point comparisons are always tricky.
