### ISSUE TITLE
Lesson 8.4 - iterator protocol badly explained

### ISSUE THREAD

**Issue by abonie** [udacity/mwnd-issues#2]
The description of iterator protocol in course materials is inconsistent with that from mdn, and the exercise is misleading too, will lead to off-by-1 errors in students future code. Please see link for more details: https://discussions.udacity.com/t/mistake-in-course-materials-lesson-8-4-iterables/440705

**Comment by forbiddenvoid** [comment]
There are a lot of issues with this quiz, so we've decided to deprecate it. Much of the practical applications of using iterators is demonstrated in later parts of the lesson.
