### ISSUE TITLE
Adding Appendix

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/mwnd-issues#3]
Message from student:
Could you add appendix with schema and code snippets for Service Worker course and IndexedDB and Caching course?
On https://mws-challenge.slack.com/, member Carlos Nogueira shared some nice notes on these courses: 
https://mws-challenge.slack.com/files/U7W0H71BP/F89JGA1T4/indexeddb.pdf 
https://mws-challenge.slack.com/files/U7W0H71BP/F8AENQU5U/service_worker.pdf

Ticket #649480

**Comment by forbiddenvoid** [comment]
I'm not in this Slack community.
