### ISSUE TITLE
Built-ins symbols error

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/mwnd-issues#5]
https://classroom.udacity.com/courses/ud899-emea/lessons/1b997dce-e2ce-4246-b5ae-d39ca175f887/concepts/100b565f-0e61-42e9-a2f4-332aa2f1a1b6

"[...] because the description is only used to described the symbol. [...]" 
Please correct "described".

**Comment by micheledallatorre** [comment]
Thanks for creating the issue. :+1:

**Comment by forbiddenvoid** [comment]
Fixed.
